/**
 * Writes the security rules out with the two real addresses filled in.
 *
 *   npm run rules
 *
 * Why this exists: the rules have to know which two addresses are allowed, and
 * so does the app. Keeping that fact in two hand-edited files and one env file
 * is three places to get it wrong, and the failure mode is silent — the rules
 * simply deny everything and the garden looks broken for no visible reason.
 *
 * So .env.local is the only place the addresses are written, and this generates
 * the rest. The templates keep placeholders and are safe to commit; the output
 * has real addresses in it and is ignored.
 */

import { mkdirSync, readFileSync, writeFileSync } from 'node:fs'
import { dirname, join } from 'node:path'
import { fileURLToPath } from 'node:url'

const root = join(dirname(fileURLToPath(import.meta.url)), '..')
const OUT = join(root, 'rules-out')

function envFile() {
  try {
    return readFileSync(join(root, '.env.local'), 'utf8')
  } catch {
    fail('No .env.local. Copy .env.example to .env.local first.')
  }
}

function fail(message) {
  console.error(`\n  ${message}\n`)
  process.exit(1)
}

function read(env, key) {
  const line = env.split('\n').find((l) => l.trim().startsWith(`${key}=`))
  const value = line?.slice(line.indexOf('=') + 1).trim() ?? ''
  if (value === '') {
    fail(
      `${key} is empty in .env.local.\n` +
        `  Both addresses have to be filled in — without them the rules would\n` +
        `  either lock you both out or let anyone in, and neither is worth guessing.`,
    )
  }
  return value.toLowerCase()
}

const env = envFile()
const warm = read(env, 'VITE_WARM_EMAIL')
const cool = read(env, 'VITE_COOL_EMAIL')

if (warm === cool) {
  fail('VITE_WARM_EMAIL and VITE_COOL_EMAIL are the same address.')
}

mkdirSync(OUT, { recursive: true })

/**
 * Where each one goes, in the order the console wants them.
 *
 * The order is not arbitrary: Firestore first because everything else in the
 * garden is dead without it, Storage last because it is the one that did not
 * exist until the Glasshouse and is therefore the one that gets forgotten.
 */
const FILES = [
  {
    name: 'firestore.rules',
    where: 'Firestore Database → Rules',
    what: 'Everything that is kept: the letters, the games, the memories, the car.',
    fence: 'js',
  },
  {
    name: 'database.rules.json',
    where: 'Realtime Database → Rules',
    what: 'Presence only — where the two of you are standing, right now.',
    fence: 'json',
  },
  {
    name: 'storage.rules',
    where: 'Storage → Rules',
    what: 'The bytes: photographs in the Glasshouse, voice-lights in the Stars.',
    fence: 'js',
  },
]

const filled = FILES.map((file) => ({
  ...file,
  body: readFileSync(join(root, file.name), 'utf8')
    .replaceAll('__WARM_EMAIL__', warm)
    .replaceAll('__COOL_EMAIL__', cool),
}))

for (const file of filled) {
  writeFileSync(join(OUT, file.name), file.body)
  console.log(`  wrote rules-out/${file.name}`)
}

/*
  And all three in one file, in paste order.

  Three files in a folder is three chances to publish two of them, and the
  failure mode of publishing two of them is a garden that works until the
  moment somebody hangs a photograph. One document, in order, each block
  labelled with the screen it belongs on, is a checklist you can hold your
  thumb against — which is what this actually is at the console.
*/
const bundle = [
  '# Paste these three, in this order',
  '',
  `Generated by \`npm run rules\` on ${new Date().toISOString().slice(0, 10)}.`,
  `Filled in for **${warm}** (warm) and **${cool}** (cool).`,
  '',
  '**This file has real addresses in it and is gitignored.** Regenerate it',
  'rather than keeping it, and re-run this command any time either address',
  'changes — the addresses are compiled into all three.',
  '',
  'Nothing takes effect until you press **Publish** on each screen. All three.',
  '',
  ...filled.flatMap((file, i) => [
    '---',
    '',
    `## ${i + 1}. ${file.where}`,
    '',
    file.what,
    '',
    `\`\`\`${file.fence}`,
    file.body.trimEnd(),
    '\`\`\`',
    '',
  ]),
].join('\n')

writeFileSync(join(OUT, 'PASTE-ME.md'), bundle)
console.log('  wrote rules-out/PASTE-ME.md')

console.log(`
  Both filled in with:
    warm  ${warm}
    cool  ${cool}

  Open  rules-out/PASTE-ME.md  and work down it. All three, in order,
  Publish on each. Nothing reads any of them until you do.

  (The three files are beside it if you would rather copy them one at a time.)
`)
